repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: check-added-large-files
        exclude: ^migrations/versions/static_data/(unleashlive|mary)\.wkt$
      - id: mixed-line-ending
        args: [ --fix=lf ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        exclude: ^alembic/
        additional_dependencies:
          - types-Flask
          - types-Werkzeug
        stages:
          - manual
        args: [--install-types, --non-interactive]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.8.1
    hooks:
      - id: ruff-format
        types_or: [python, pyi, jupyter]
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        types_or: [python, pyi, jupyter]
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.2.5
    hooks:
      - id: sqlfluff-fix
  - repo: https://github.com/crate-ci/typos
    rev: v1.28.1
    hooks:
      - id: typos
        args: [
          --force-exclude,
          # --write-changes (Don't use this to stop typos making auto-corrections)
        ]
